### ISSUE TITLE
Does this accoutn for the upped cooldown on attempts?

### ISSUE THREAD

**Issue by dev-ious** [m3talstorm/ArkLockBot#1]
Dev's said this;

There is a 10s delay on pincode guessing after each attempt. We're increasing it a little more than that, but pincode spammers don't really work efficiently, as long as you use a good pin. - The Right Hand

Does the script take this into account? Doesn't seem like it, since 27+ hours for all combos is about right i'd think.

**Comment by m3talstorm** [comment]
No this was written months ago, and I havent been following Ark since then.

**Comment by dev-ious** [comment]
Thanks for the reply. Ok, well I think I may be able to modify the script to account for the delay.. I'll see what I can do. :+1:
