### ISSUE TITLE
the true pincode doesn't unlock gate

### ISSUE THREAD

**Issue by btronquo** [m3talstorm/ArkLockBot#2]
Hi, 

Thanks for your job for this macro on AHK
however, it seem to don't work anymore

I tested with a friend with a different team on ark . His pin code is 1532.
I had start the script with 1530 and put a 1540 for final code. 
The script reached the pincode 1532 but nothing happened.. strange no ?

I added a bit of code in your script to really simulate a personne (just a delay between each key pressed)
but nothing work.. 
The tooltip show me '1532'. The log show me '1532'. The pincode seems to be correctly input but the windows close, and it test another one, etc etc...

Have you any idea ?

Sorry for my english by the way :s 

++

**Comment by m3talstorm** [comment]
HI @btronquo sorry for the late reply. This tool was created a good few years ago now when Ark was in the early stages/beta development.

The tool does not detect when it opens the door. When it reaches the correct code it will unlock the door, but it will continue to try more. This is why you need to keep a loose eye on it so you can record the code and stop the tool.

I haven't played Ark in a while, but from what i've heard there is a shock when you get the code wrong a few times and maybe an increased delay as well?

**Comment by andiwand** [comment]
you have to use a 19s sleep between the attempts. at least that worked for me... kinda ruining this method

**Comment by m3talstorm** [comment]
@andiwand is that because of Ark? Have they added a long wait time? Or is your PC/net on the slow side?

**Comment by andiwand** [comment]
yeah, they fixed it. the client shows nothing about this, its just like
entering the wrong pin.

On Thu, Mar 30, 2017, 19:41 Metalstorm <notifications@github.com> wrote:

@andiwand <https://github.com/andiwand> is that because of Ark? Have they
added a long wait time? Or is your PC/net on the slow side?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/m3talstorm/ArkPincodeCracker/issues/2#issuecomment-290486380>,
or mute the thread

**Comment by btronquo** [comment]
Omg i'm so late sorry 

Hi @m3talstorm @andiwand 
Yes 19s that's right .. 

hard times ;) 

By the way, good job ;)

**Comment by dheepak007** [comment]
HEY metalstorm

i know its too late.. but wana know that does this script in AHK get detected by battle eye ?... still am confused that it may get detected ..

**Comment by m3talstorm** [comment]
@dheepak007 No idea, haven't played or kept up with Ark in a long long time. You can assume this no longer works.
